# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 527cfb5f5cb3267a64728fd68553b89906b637a6bdda98818c26de7ed7fd3b85f70ba00f74c2e5fc48ee39ffa470b07fe13ac41778094628607a3b245fd65b8d

test:
  secret_key_base: 602ca228b3c31e54e21c2974b34712b9773b591811ee48de8398533e20e97d01e2a9f883f5dcb0111ef102cabd7a3076ae5388dafb6b72e1e3b82789934299da

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
